/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { UtilType } from "./util-types";
export { UtilType } from "./util-types";
export namespace Components {
    interface SubComponent {
    }
}
export interface SubComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSubComponentElement;
}
declare global {
    interface HTMLSubComponentElementEventMap {
        "someEvent": UtilType;
    }
    interface HTMLSubComponentElement extends Components.SubComponent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSubComponentElementEventMap>(type: K, listener: (this: HTMLSubComponentElement, ev: SubComponentCustomEvent<HTMLSubComponentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSubComponentElementEventMap>(type: K, listener: (this: HTMLSubComponentElement, ev: SubComponentCustomEvent<HTMLSubComponentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSubComponentElement: {
        prototype: HTMLSubComponentElement;
        new (): HTMLSubComponentElement;
    };
    interface HTMLElementTagNameMap {
        "sub-component": HTMLSubComponentElement;
    }
}
declare namespace LocalJSX {
    interface SubComponent {
        "onSomeEvent"?: (event: SubComponentCustomEvent<UtilType>) => void;
    }
    interface IntrinsicElements {
        "sub-component": SubComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sub-component": LocalJSX.IntrinsicElements["sub-component"] & JSXBase.HTMLAttributes<HTMLSubComponentElement>;
        }
    }
}
